name: Go

on:
  push:
    branches: [ main ]
    paths:
      - "**.go"
      - "**.s"
  pull_request:
    branches: [ main ]
    paths:
      - "**.go"
      - "**.s"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
      env:
        UNIALERTS_TEST_DISCORD_ID: ${{ secrets.UNIALERTS_TEST_DISCORD_ID }}
        UNIVERSALIS_ALERTS_DISCORD_TOKEN: ${{ secrets.UNIVERSALIS_ALERTS_DISCORD_TOKEN }}
